### ISSUE TITLE
[Feature-request] vcpkg support

### ISSUE THREAD

**Issue by gc435** [boost-ext/sml#281]
Would you consider putting **Boost.SML** into **vcpkg**?  I know it's only a header, and trivial to install, but **vcpkg** is just so nice.  At the very least, it would cause some people to find out about **Boost.SML** for the first time.

An example: https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-github-repos.md

**Comment by pschiager** [comment]
I see this issue is open, while "bext-sml" is listed in the vcpkg browser https://vcpkg.io/en/packages.

**Comment by krzysztof-jusiak** [comment]
Thanks @pschiager looking at it. Yeah, the version should be updated, though I'm not sure how that is being done, I guess it's not automated?

**Comment by pschiager** [comment]
I think you are right, as far as I understand an issue and/or PR is the way to go: https://github.com/microsoft/vcpkg#contributing

**Comment by pschiager** [comment]
@krzysztof-jusiak I simply created an issue in the vcpkg repo, as there is a template for updating versions. [https://github.com/microsoft/vcpkg/issues/38606](https://github.com/microsoft/vcpkg/issues/38606)

**Comment by krzysztof-jusiak** [comment]
Thank you @pschiager for talking care of that. Appreciate it.

**Comment by pschiager** [comment]
@krzysztof-jusiak Perhaps this can be closed now.
