### ISSUE TITLE
How to handle exception outside of state machine?

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [boost-ext/sml#333]
Hi!

I have the following example:
```
#include <boost/sml.hpp>
#include <cassert>
#include <iostream>
#include <stdexcept>

namespace sml = boost::sml;

namespace {

struct error_handling {
    auto operator()() const {
        using namespace sml;
        return make_transition_table(
                *("idle"_s) + "event1"_e / [] () noexcept(false) { throw std::runtime_error{"error"}; } = X
        );
    }
};
}  // namespace

int main() {
    try
    {
        using namespace sml;
        sm<error_handling> sm;

        sm.process_event("event1"_e());  // throws runtime_error
    }
    catch(...)
    {
    }
}
```

But my program is terminated by unhandled exception. I've investigated a little bit and found that it tries to process event in `noexcept` context. Firing an exception in `noexcept` terminates my program.

Is there any ways how to fix it, except adding to the transition table `exception` states?

Thank you.

**Comment by codentary** [comment]
I have the same issue  and did not find a good way around it.

As a workaround I can use `#define BOOST_SML_DISABLE_EXCEPTIONS true` before including `sml.hpp` which will make `sml` use function versions without `noexcept` , but this is not great as `BOOST_SML_DISABLE_EXCEPTIONS` is intended to use when the program is compiled without exceptions, which is not true here.
I am not sure if this solution might  lead to inconsistencies in the state machine.

Another thing I was thinking was to use `sml::exception<std::exception>` to catch and log the exception and at least `process_event` would return false back to me, but this is not the case, at least not if I throw from inside an action, probably 
works for guards, so still not enough.

**Comment by krzysztof-jusiak** [comment]
If you don't handle the exception in the state machine explicitly (via exception<...>) the exception itself should be propagted outside the process_event call (leaked) so that you could handle it outside :thinking:

**Comment by codentary** [comment]
Yes, I would expect the same, but because `process_event` is declared with `noexcept`,  when an exception is thrown, `terminate` gets called which in turn calls `abort`.

**Comment by krzysztof-jusiak** [comment]
Yeah, that's a bug then `noexcept` should be optional and set with `noexcept(has_exceptions)`.
Let me fix that :point_up:

**Comment by codentary** [comment]
Great, thanks. I will test it as soon as you have it.

**Comment by codentary** [comment]
Tested, works fine.
