### ISSUE TITLE
[v1.1.2] sizeof(sm) changed for GCC 10.x

### ISSUE THREAD

**Issue by anb0s** [boost-ext/sml#351]
We have updated to version 1.1.2 and now internal compile test failed:
```
|   static_assert(hello::smSize == sizeof(sm), "sizeof(sm) != 1b");
|                 ~~~~~~~~~~~~~~^~~~~~~~~~~~~
```

and unittest also failed as now the size is 15 bytes?:
```
Expected equality of these values:
  (size_t)1
    Which is: 1
  sizeof(sm)
    Which is: 15
[  FAILED  ] SmlHelloModuleTest.CheckStates (1 ms)

```

**Comment by anb0s** [comment]
looks related to #348 and #349

**Comment by ooxi** [comment]
Yes, it's related to that change. Unfortunately the empty array optimization does no longer work for GCC 10.

The current solution is only a workaround. I'm working on extracting an example where the empty array optimization breaks state machines.

For now I suggest using 1.1.1 or ignoring build failure.

**Comment by krzysztof-jusiak** [comment]
It seems to work again :thinking: Fixed by https://github.com/boost-ext/sml/pull/378
