### ISSUE TITLE
Using SML with TI TM4C Devices

### ISSUE THREAD

**Issue by TunaBicim** [boost-ext/sml#387]
Hello Everyone,

I am trying to use C++ on embedded projects and since my company uses 
state machines a lot, this seemed like a good way to start.

How would I go about using Boost SML with TI ARM compiler? 

If I try to add use an example 
project I get tons of compiler errors seen on the attached picture.
![capture](https://user-images.githubusercontent.com/36315935/92064119-d4291580-ed6a-11ea-917e-dbcffa9ef907.PNG)

I am sorry if this seems like a basic question. I am new to using C++ on embedded and also using external libraries besides vendor supplied ones. 

Thanks.

**Comment by krzysztof-jusiak** [comment]
Can you elaborate which ARM compiler are you using and which C++ standard, please?
The following seems to work on ARM-9.2-gcc with C++17 - https://godbolt.org/z/fYcvnj

**Comment by TunaBicim** [comment]
I was using TI's own arm compiler. I switched to GCC and set it to C++17 and it seems to work fine. 
I don't know how compliant TI's compiler is with the standards.
