### ISSUE TITLE
Regression: Accessing SM and dependencies in an action doesn't work

### ISSUE THREAD

**Issue by gischthefish** [boost-ext/sml#399]
According to the fix/commit [2095f08acaca73ad4fde89488b7611606f4a555e](https://github.com/boost-ext/sml/commit/2095f08acaca73ad4fde89488b7611606f4a555e) (Add support for injecting sm into guard/actions) it should be possible to access the SM and dependencies in an action. But with SML v1.1.3 even this [example](https://github.com/boost-ext/sml/issues/94#issuecomment-310989485) from the author doesn't compile anymore.

I get the following error:
/usr/local/oecore-x86_64_tux_dunfell/sysroots/armv5te-angstrom-linux-gnueabi/usr/include/boost/sml.hpp:1853:18: error: no match for call to ‘(boost::ext::sml::v1_1_3::aux::zero_wrapper<table::operator()() const::<lambda(const auto:3&, auto:4&, my_dep&)>, void>) (const e1&, boost::ext::sml::v1_1_3::back::sm_impl<boost::ext::sml::v1_1_3::back::sm_policy<table> >&, boost::ext::sml::v1_1_3::aux::pool<>&, boost::ext::sml::v1_1_3::aux::pool<boost::ext::sml::v1_1_3::back::sm_impl<boost::ext::sml::v1_1_3::back::sm_policy<table> > >&)’
 1853 |     return object(event, sm, deps, subs);
      |            ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
main4.cpp:38:35: note: candidate: ‘template<class auto:3, class auto:4> table::operator()() const::<lambda(const auto:3&, auto:4&, my_dep&)>’
   38 |             *"s1"_s + event<e1> / [](const auto& ev, auto& sm, my_dep& dep) {
      |                                   ^
main4.cpp:38:35: note:   template argument deduction/substitution failed:
In file included from main4.cpp:22:
/usr/local/oecore-x86_64_tux_dunfell/sysroots/armv5te-angstrom-linux-gnueabi/usr/include/boost/sml.hpp:1853:18: note:   candidate expects 3 arguments, 4 provided
 1853 |     return object(event, sm, deps, subs);
      |            ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~

## Specifications

  - SML v.1.1.3
  - GCC 9.3.0

**Comment by gischthefish** [comment]
I forgot to mention, that either accessing SM or dependencies work, but not both at the same time, i.e. if the signature of the action cannot include SM and a dependency at the same time, but each alone works.

**Comment by krzysztof-jusiak** [comment]
The implementation of this feature has changed to avoid recursive calls and be compliant with the UML-2.5

Example

```cpp
s1 + event<e1> / [](sml::back::process<e2, e3> processEvent) -> void {
            processEvent(e2{});
            processEvent(e3{});
          }
```

The process_queue has to be specified when defining sm

```cpp
  sml::sm<c, sml::process_queue<std::queue>> sm{};
```

Full example
* https://github.com/boost-ext/sml/blob/master/test/ft/actions_process.cpp#L171
