### ISSUE TITLE
on_entry triggered twice when event is pushed from action

### ISSUE THREAD

**Issue by cppden** [boost-ext/sml#427]
## Expected Behavior
on_entry action is triggered once only when state is entered

E.g.: in example below the output is:
```
Connected without link
Set link
Sending REG_REQ...
Close
```

## Actual Behavior
on_entry action called twice when event is passed to SM in action

E.g.: in example below the output is:
```
Connected with link
Set link
Sending REG_REQ...
Sending REG_REQ...
```

## Steps to Reproduce the Problem
https://godbolt.org/z/qzdxYv
the code sample contains both cases (evEstablished):
  1. event is pushed externally.
  2. event is pushed from action (e.g. due to connection is established synchronously).

## Specifications

  - Version: 1.1.3

**Comment by Rijom** [comment]
Interesting. Looks like there is an issue with entering the Connecting state as well.

```
Disconnected   ----------------------->   Connecting   -------------->   Registering   ->   Connected
                evConnect                               evEstablished
                triggers evEstablished
```

- on_entry for Connecting is not called at all
- the action for evEstablished is executed once
- on_entry to Registering is called twice


https://godbolt.org/z/h5rj9b

**Comment by cppden** [comment]
turns out there's a way to do this properly in sml though it looks a bit strange but worst it's neither mentioned in the docs nor in examples.

thanks a lot to @redboltz for providing example on [stackoverflow](https://stackoverflow.com/questions/58524500/boost-state-machine-language-post-event-from-within-an-action)!

**Comment by Rijom** [comment]
Is this areal solution though? Maybe it should be noted in the documentation not to process events in an action?
