### ISSUE TITLE
Add SML to Conan-Center

### ISSUE THREAD

**Issue by mpusz** [boost-ext/sml#438]
Could you please consider adding SML to Conan-Center? It is quite simple: https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md. I can help if needed.

**Comment by krzysztof-jusiak** [comment]
Hi @mpusz, oh I'm totally up for it, don't have much experience doing so, though :disappointed: Any help more than appreicated :pray: thanks!

**Comment by mpusz** [comment]
Great! 😃 
I will add an initial version there but it is you that should provide support for new future library releases. I will provide HowTo instructions here when my changes will be merged into ConanCenter.

**Comment by mpusz** [comment]
It took quite some time to start but I am on it now (conan-io/conan-center-index#4591). The only things to resolve are:
- it would be great if you could add a LICENSE (or LICENSE.md) file to the repo so https://github.com/conan-io/conan-center-index/pull/4591/files#diff-6f79cfb126967b39e0d6360a6400e965a14957e42fb0cc82f3f068854ac45b9eR29 does something ;-) (without it the conan build will fail)
- I noticed that static_assert https://github.com/conan-io/conan-center-index/pull/4591/files#diff-b5529e798d1dfa3dec8083d79698f1b1b6643f7a950331fbc5608e890b4a63e8R48 fails while I try the recipe on gcc-10.2. Do you have any suggestions?

BTW, you can check it by yourself with:
- pull and checkout https://github.com/mpusz/conan-center-index/tree/sml
- `cd recipes/sml/all`
- `conan create . 1.1.3@`

**Comment by krzysztof-jusiak** [comment]
Oh, fantastic, thank you @mpusz :pray:

**Comment by krzysztof-jusiak** [comment]
Sure, I'll add LINCESE.md

**Comment by mpusz** [comment]
BTW, the build on ConanCenter failed with: https://github.com/conan-io/conan-center-index/pull/4591#issuecomment-780075022 on gcc 4.9. What are the compiler constraints for the library, should I force any specific C++ version standard in CMake?

**Comment by mpusz** [comment]
I forced C++14 and it seems to improve the build. However, now it fails on https://github.com/conan-io/conan-center-index/pull/4591#issuecomment-780084548. We need this license.md and a new release tag that will include this file.

**Comment by krzysztof-jusiak** [comment]
Thanks, @mpusz 
New release with the LICENSE file https://github.com/boost-ext/sml/releases/tag/v1.1.4

**Comment by mpusz** [comment]
Done! https://conan.io/center/sml 😃

**Comment by krzysztof-jusiak** [comment]
Fantastic, thank you @mpusz :pray:
