### ISSUE TITLE
Cannot use library with cmake and MSVC 19.28.29337.0

### ISSUE THREAD

**Issue by Stuv7CB** [boost-ext/sml#445]
## Expected Behavior
Cmake generates solution files for sml

## Actual Behavior
```
1> [CMake] -- The CXX compiler identification is MSVC 19.28.29337.0
1> [CMake] -- Detecting CXX compiler ABI info
1> [CMake] -- Detecting CXX compiler ABI info - done
1> [CMake] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
1> [CMake] -- Detecting CXX compile features
1> [CMake] -- Detecting CXX compile features - done
1> [CMake] -- Performing Test HAS_CXX14_FLAG
1> [CMake] -- Performing Test HAS_CXX14_FLAG - Failed
1> [CMake] -- Performing Test HAS_CXX17_FLAG
1> [CMake] -- Performing Test HAS_CXX17_FLAG - Failed
1> [CMake] -- Performing Test HAS_CXX20_FLAG
1> [CMake] -- Performing Test HAS_CXX20_FLAG - Failed
1> [CMake] CMake Error at C:\Users\UserName\Documents\sml\CMakeLists.txt:56 (message):
1> [CMake]   sml requires c++14
```
## Steps to Reproduce the Problem

  1. `mkdir build && cd build`
  1. `cmake ..`

## Specifications

  - Version: 1.1.4
  - Platform: Microsoft Windows 10 x64 MSVC 19.28.29337.0
  - Subsystem:

**Comment by thpoll83** [comment]
As work-around you can just replace
`elseif(HAS_CXX17_FLAG)`
with 
`elseif(HAS_CXX17_FLAG OR "${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")`
in CMakeLists.txt
Add an additional MSVC version number check if that makes you feel better ;)

**Comment by Stuv7CB** [comment]
It seems that 3eb279a43b4fc7f27ec625bed30e11734759c2cf commit fixed this
