### ISSUE TITLE
where is euml2.hpp?

### ISSUE THREAD

**Issue by cmorganBE** [boost-ext/sml#452]
I've looked all over and can't find any reference on google or packages.ubuntu.com or on the boost website or in any version change info about euml2.hpp. Did this file exist at some point and was removed? Is it new and not yet in a boost package (even though google can't find it?) How are there tests that include it, and a test named euml2.cpp even.... I'm so confused...

## Expected Behavior
Build works.
## Actual Behavior

Compiler errror due to missing boost msm euml2.hpp file:

```
make[2]: Entering directory '/home/cmorgan/projects/sml/build'
[  5%] Building CXX object benchmark/complex/CMakeFiles/complex_euml2.dir/euml2.cpp.o
cd /home/cmorgan/projects/sml/build/benchmark/complex && /usr/bin/c++ -DBOOST_ALL_NO_LIB -DBUILD_SHARED_LIBS=OFF -DCHECK_COMPILE_TIME -I/home/cmorgan/projects/sml/include -I/home/cmorgan/projects/sml/benchmark -I/home/cmorgan/projects/sml/benchmark/header -Wno-unused-local-typedefs -Wno-unused-parameter -std=gnu++2a -o CMakeFiles/complex_euml2.dir/euml2.cpp.o -c /home/cmorgan/projects/sml/benchmark/complex/euml2.cpp
/home/cmorgan/projects/sml/benchmark/complex/euml2.cpp:14:10: fatal error: boost/msm/front/euml2/euml2.hpp: No such file or directory
   14 | #include <boost/msm/front/euml2/euml2.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [benchmark/complex/CMakeFiles/complex_euml2.dir/build.make:82: benchmark/complex/CMakeFiles/complex_euml2.dir/euml2.cpp.o] Error 1
```

## Steps to Reproduce the Problem

  1.Build master

## Specifications

  - Version: master
  - Platform: Ubuntu 21.04
  - Subsystem: benchmark/complex

**Comment by krzysztof-jusiak** [comment]
https://github.com/boostorg/msm/blob/euml2/include/boost/msm/front/euml2/euml2.hpp
