### ISSUE TITLE
Possible to conditionally transition to states based on a single event?

### ISSUE THREAD

**Issue by cmorganBE** [boost-ext/sml#480]
I have a use case where an event comes in and depending on the event content I'd like to transition to one of a couple of states.

For example I'd like to use the content of SensorData to determine a transition to one of a few states:

```
          , sml::state<waiting_for_printing_start_s4_s> + event<SensorData> [ &Self::guard_sensor_data ] = sml::state<complete_s5_s>
          , sml::state<waiting_for_printing_start_s4_s> + event<SensorData> [ &Self::guard_sensor_data ] = sml::state<fault_s6_s>
```

I didn't see anything in the tutorial or examples but this would be super helpful functionality that I could work around by sending myself an event that is processed by the higher level event processing code but its not as clean.

Is there a way to transition internal to the guard function or another better approach that I should consider using?

**Comment by luan-young** [comment]
Hi!
I think there is plenty documentation examples that illustrates that use case in different ways. One of them would be something like that:
```
auto const guard1 = [](auto const& event) {
    return event.guard_sensor_data == condition1;
};
auto const guard2 = [](auto const& event) {
    return event.guard_sensor_data == condition2;
};

// then in the transition table...
, state<waiting_for_printing_start_s4_s> + event<SensorData> [ guard1 ] = state<complete_s5_s>
, state<waiting_for_printing_start_s4_s> + event<SensorData> [ guard2 ] = state<fault_s6_s>
```
I think guard1 and guard2 should be always mutually exclusive so you don't rely in processing order.
Notice that your guards could capture other dependencies injected to the SM as well, so you could use them in the condition expression. Again, there are plenty of examples showing how to do that sort of things.
I hope that helps you.

**Comment by cmorganBE** [comment]
Ahh. Thank you for confirming this could work. I ended up dispatching myself events by pushing them up to the upper layer which then pushes them back down in order.

It wasn't obvious to me, and I didn't test, that it was possible to have multiple table entries for a given event.

After looking I do see there is one example that shows the same state, same event, with different guards. It was hard to spot!
