### ISSUE TITLE
How to handle not handled events because of wrong state?

### ISSUE THREAD

**Issue by werto87** [boost-ext/sml#486]
Context:
In a system where a user can send events which are handled by a state machine. It is possible that the user sends an event and the state machine can not handle it because it is in the wrong state. I want to inform the user that the state machine is in a state in which it can not handle the event.

Example:
In the following example the second "sm.process_event (start{});" call is ignored because the state machine is in a state which does not handle the start event.
```cpp
#include <boost/sml.hpp>
#include <iostream>
struct start{};
int
main ()
{
  namespace sml = boost::sml;
  sml::front::sm sm = [] {
    using namespace sml;
    // clang-format off
    return make_transition_table (
      *"state0"_s + event<start> / [] { std::cout << "action\n"; } = "state1"_s
      );
    // clang-format on
  };
  sm.process_event (start{});
  sm.process_event (start{});
}
```
On the second "sm.process_event (start{});" call I want to print something like:
event not handled in this state. current state: 'state1' event 'start'.
Possible solution:
Add "event<_> " for every state:
```cpp
#include <boost/sml.hpp>
#include <iostream>

struct start{};
struct stop{};
int
main ()
{
  namespace sml = boost::sml;
  sml::front::sm sm = [] {
    using namespace sml;
    // clang-format off
    return make_transition_table (
      * "state0"_s   + event<start>  / [] { std::cout << "start\n"; }  = "state1"_s
      , "state0"_s  + event<_>   / [] { std::cout << "event<_>\n"; } 
      , "state1"_s  + event<stop>   / [] { std::cout << "stop\n"; } 
      , "state1"_s  + event<_>   / [] { std::cout << "event<_>\n"; } 
      );
    // clang-format on
  };
  sm.process_event (start{});
  sm.process_event (start{});
}
```
Is there a solution with orthogonal regions something like 
`, *("unexpected events handling"_s) + unexpected_event<some_event> / [] { std::cout << "unexpected event 'some_event'" << std::endl; }`?

This would be nice so I do not have to add "event<_>" for every state.

**Comment by Rijom** [comment]
Consider the return value of process_event. I think it is false in cases where the state-machine does not have an appropriate transition to take.
