### ISSUE TITLE
Choosing when to switch active states

### ISSUE THREAD

**Issue by keremcc** [boost-ext/sml#509]
Does boost sml provide option to decide in which action we switch active state as provided in boost msm ?

![image](https://user-images.githubusercontent.com/47608531/177589671-ad4349a0-e51b-4e0a-8157-976e9617684c.png)
https://www.boost.org/doc/libs/1_65_1/libs/msm/doc/HTML/ch03s05.html#d0e2714

**Comment by Rijom** [comment]
No. But SML has the same behaviour as MSM by default: active_state_switch_after_entry.

**Comment by keremcc** [comment]
Thanks for the reply, I guess we can close this issue.
