### ISSUE TITLE
Generate new v1.1.6 version

### ISSUE THREAD

**Issue by ladislas** [boost-ext/sml#512]
A lot has happened since https://github.com/boost-ext/sml/releases/tag/v1.1.5

A new version would be nice :)

I tried generating the single header by myself on macOS, but it doesn't work, the final output is almost empty.

Any clues on how to fix that?

**Comment by krzysztof-jusiak** [comment]
Thank, I'll do it; let's realese it; usualy tools/pph.ssh should work but sometimes there are changes just done in the hpp file so will have to backpoert

**Comment by krzysztof-jusiak** [comment]
Release as - https://github.com/boost-ext/sml/releases/tag/v1.1.6

**Comment by ladislas** [comment]
Thanks so much!
