### ISSUE TITLE
What's the best practice to create a fully created state transition table?

### ISSUE THREAD

**Issue by wuyuanyi135** [boost-ext/sml#538]
I want to create a state transition table consists of many states (`S_n`) and they can transit from any state to any other one state with an event like `Goto{3}`. In some other state machine library I could decide which state to go in the event handling function. In `sml` I have to create a large transition table with `n!` number of guarded transitions.
Is there any convinent approach to design such a state machine without create the tedious state transition table?
![screenshot-20221024-040850](https://user-images.githubusercontent.com/11760870/197415771-45d42f26-9009-41c9-82f8-1f8ee7d2bbd5.png)

Thanks!

**Comment by madf** [comment]
@wuyuanyi135 how did you solve this problem?
