### ISSUE TITLE
Persisting State

### ISSUE THREAD

**Issue by Schoppenglas** [boost-ext/sml#547]
I want to persist my state machine and recover it in a later moment. I found "sm.set_current_states("s1"_s)". What I am missing is something like "sm.get_current_states() -> int(s)" and "sm.set_current_states(int(s)) -> void". I wrote a function which can extract the ID's of all states:

```cpp
template <template <class...> class T, class... Ts>
auto extract_states(const T<Ts...> &) {
  return std::array<std::string_view, sizeof...(Ts)>{ ( sml::aux::string<typename sml::front::state<Ts>::type>{}.c_str() )... };
}
```

This function I can call with
```cpp
auto states = extract_states(decltype(sm)::states{});
```

Now I could use a visitor and do string comparison every time the state changes and persist this ID. But I am curious if there is better solution.

Also, at the moment, i have no clue how to convert back my ID to a state<> which i can use with the current "sm.set_current_states("s1"_s)" function.

Hopefully anybody can help me.

**Comment by Schoppenglas** [comment]
I wrote this function, which checks if a state is present in the transition table.

```cpp
template <template <class...> class T, class... Ts>
bool state_exists_impl(const std::string_view state, const T<Ts...> &)
{
    const auto states = std::array<std::string_view, sizeof...(Ts)>{
        (boost::sml::aux::string<typename boost::sml::front::state<Ts>::type>{}.c_str())...};

    return std::any_of(
        states.cbegin(), states.cend(), [state](const std::string_view entry) { return state == entry; });
}

template <class SM>
bool state_exists(SM &, const std::string_view state)
{
    return state_exists_impl(state, typename SM::states{});
}
```

Maybe this helps someone.

**Comment by Schoppenglas** [comment]
Another helpful function, with this one one can set current state by name.

```cpp
template <class SM, typename T>
void set_state_impl(SM &sm, const std::string_view state)
{
    if (boost::sml::aux::string<typename boost::sml::front::state<T>::type>{}.c_str() == state)
    {
        sm.set_current_states(boost::sml::front::state<T>{});
    }
}

template <class SM, template <class...> class T, class... Ts>
void set_state_impl(const std::string_view state, SM &sm, const T<Ts...> &)
{
    (void)std::initializer_list<int>{(set_state_impl<SM, Ts>(sm, state), 0)...};
}

template <class SM>
void set_state(SM &sm, const std::string_view state)
{
    set_state_impl(state, sm, typename SM::states{});
}
```

**Comment by apotema** [comment]
@Schoppenglas I am receiving an error on the 

 error: no matching member function for call to 'set_current_states'
   33 |         sm.set_current_states(boost::sml::front::state<T>{});

Do you have an updated version of this solution?

**Comment by Schoppenglas** [comment]
> @Schoppenglas I am receiving an error on the
> 
> error: no matching member function for call to 'set_current_states' 33 | sm.set_current_states(boost::sml::front::state{});
> 
> Do you have an updated version of this solution?

U need to inject sml::testing like in https://github.com/boost-ext/sml/blob/master/example/testing.cpp

**Comment by apotema** [comment]
Is it ok to inject testing into a production environment code?
I am working on a game that needs to be saved/loaded. I am worried that using Testing may impact the performance.

**Comment by Schoppenglas** [comment]
For me it is working in production. Just check the code if u r worried.

**Comment by apotema** [comment]
It would be nice to reopen this issue as a requisition to export this function out of the testing scope so we could use it more broadly
