### ISSUE TITLE
It's possible to create state machines at runtime?

### ISSUE THREAD

**Issue by jepessen** [boost-ext/sml#551]
See a lot of examples where state machines are written directly in code.

I've the requirement for a project to build state machines at runtime. For example, the description of the state machine is in a JSON, and then I need to parse that json and create the corresponding state machine. 

I don't think that's possible to do it with `make_transition_table`, since it needs the state machine description in the constructor arguments.

So, is there a way to build a state machine at runtime or it's only possible to create them at compile time?

**Comment by Schoppenglas** [comment]
With SML it is not possible to build a state machine at runtime.

**Comment by jepessen** [comment]
Understood. Thanks for the reply.
