### ISSUE TITLE
Non-movable states are not supported, states are extensively copied during SM setup

### ISSUE THREAD

**Issue by rhaschke** [boost-ext/sml#555]
*Problem*: I have a complex state that is only movable but not copyable (e.g. because the state data comprises a non-movable unique_ptr). This scenario makes SML fail to compile.
I extended the [`data.cpp`](https://github.com/rhaschke/sml/blob/5f518d281afdbb5ec329f62b4ba527ed7fa52db7/example/data.cpp) example to understand and illustrate the problem: https://github.com/boost-ext/sml/compare/master...rhaschke:sml:issue-state-copying

*Solution*: SML should `move` states around by default and only resort to copying if that's not feasible.
Ideally, states are not copied around at all but passed via references only.

Test output of my example illustrating extensive state copying, here of the `Interrupted` state:
```
 ctor: 0
 copy ctor: 0 -> 1
 copy ctor: 1 -> 2
 copy ctor: 2 -> 3
 dtor: 2
 copy ctor: 3 -> 4
 copy ctor: 4 -> 5
 dtor: 4
 dtor: 3
 dtor: 1
 copy ctor: 0 -> 6
 copy ctor: 6 -> 7
 copy ctor: 7 -> 8
 dtor: 7
 copy ctor: 8 -> 9
 dtor: 9
 dtor: 8
 dtor: 6
 dtor: 0
127.0.0.1:1024
127.0.0.1:1024
127.0.0.1:1025
127.0.0.1:1025
 dtor: 5
```
## Specifications

  - Version: https://github.com/rhaschke/sml/tree/issue-state-copying
  - Platform: Linux Ubuntu 20.04

**Comment by rhaschke** [comment]
Closing here, as this is not a PR but an issue. See https://github.com/boost-ext/sml/issues/556 instead.

**Comment by rhaschke** [comment]
I just noticed a small remark in the docs, stating:
https://github.com/boost-ext/sml/blob/5a323c541786dab770a044baad50de984f0c6869/doc/tutorial.md#L57

I don't understand what is meant by injection and I couldn't find any hint to that in the docs yet.

Anyway, if states _must not_ comprise data members, how would you implement reusable, i.e. self-contained and configurable states? Think of [`data` class in `example/data.cpp`](https://github.com/boost-ext/sml/blob/5a323c541786dab770a044baad50de984f0c6869/example/data.cpp#L33-L34) being reused multiple times as sub states in an enclosing higher-level state machine. Where do you store the "configuration" _data_ of a state if not in the state itself? I could not find any example illustrating this. Any help is highly welcome.

**Comment by rhaschke** [comment]
Ok, I learned the hard way myself:

1. states `can` comprise data members, but their initialization must not happen via classical constructors, but via [aggregate initialization](https://en.cppreference.com/w/cpp/language/aggregate_initialization), which doesn't allow execution of user-define code during initialization.
2. In order to achieve the latter as well, one must use `Context` classes, which themselves allow for custom initialization, but which are then just _passed_ to the state via aggregate initialization.
3. This passing is automated by SML via template magic. This process is called [_dependency injection_](https://boost-ext.github.io/sml/embo-2018/#/9).

Here is a working minimal example:
```cpp
#include <boost/sml.hpp>
#include <queue>
#include <iostream>

namespace sml = boost::sml;

struct next {};
struct quit {};

const auto idle = sml::state<class idle>;
const auto s1 = sml::state<class s1>;
const auto s2 = sml::state<class s2>;

struct Context {
  Context(int data, const std::string& extra) : data(data), extra(extra) {
    std::cout << "ctx: user-defined ctor: " << this << std::endl;
  }
  int data;
  const std::string extra;
};

int main() {
  struct sub {
    // sub must not have a constructor!
    Context ctx;  // state-local data

    auto operator()() const noexcept {
      using namespace sml;
      // clang-format off
      return make_transition_table(
        * s1   + on_entry<_> / (&sub::method, process(quit{}), process(next{}))
        , s2   + on_entry<_> / (process(quit{}), process(next{}))
        , s1   + event<next> = s2
        , s2   + event<next> = s1
      );
      // clang-format on
    }
    void method() { std::cout << &ctx << " method: " << ctx.data << " " << ctx.extra << std::endl; }
  };

  struct parent {
    sml::front::state_sm<sub>::type s;

    auto operator()() noexcept {
      using namespace sml;
      // clang-format off
      return make_transition_table(
        * idle + event<next> = s
        , s + event<quit> / [this] { std::cout << "quitting\n"; } = X
      );
      // clang-format on
    }
  };

  Context c(42, "Hello"); // initialize context with custom ctor
  sub s{c}; // initialize sub-state by passing c via aggregate initialization

  sml::sm<parent, sml::process_queue<std::queue>> sm(s); // inject initialized sub state into state machine

  sm.process_event(next{});
  sm.process_event(next{});  // + process(e2{})
}
```

**Comment by rhaschke** [comment]
The `Context` must be copyable (movable is not sufficient) and it is still copied a few times:
```
ctor:   1
copy c: 1 -> 2
copy c: 2 -> 3
copy c: 3 -> 4
copy c: 2 -> 5
method: 42, Hello (2)
quitting
```

**Comment by uyha** [comment]
I tried your [data.cpp](https://github.com/rhaschke/sml/blob/5f518d281afdbb5ec329f62b4ba527ed7fa52db7/example/data.cpp) with some modifications. It seems fine for me, you can check at [here](https://godbolt.org/z/zrM158rhc). Also, maybe you can post a Godbolt link next time since it's easier to try out what is wrong.

**Comment by uyha** [comment]
I modified your example to create variables instead of temporaries, it seems to make fewer copy constructor calls. You can check [here](https://godbolt.org/z/GbYz1dr85). Also, maybe you can provide a Godbolt link instead of forking the project since it's easier to try out what you're talking about.
