### ISSUE TITLE
on_entry actions only allow for lambda expressions?

### ISSUE THREAD

**Issue by rhaschke** [boost-ext/sml#557]
## Expected Behavior

Can use anything with function semantics, namely also free function or static member function pointers, as callbacks for `on_entry` / `on_exit` events.

Ideally, if a state provides an `void on_entry()` member function, that one should be considered too.

Only allowing free functions renders writing reusable code much harder. I was trying to implement a stateful state (having member `data`), which should be incremented on each entry of the state, for example. Using a global variable instead would be awful.

## Actual Behavior

Trying to bind free functions or member functions makes the compiler fail. 

## Steps to Reproduce the Problem

  1. Compile [`example/entry_actions.cpp` on my fork](https://github.com/rhaschke/sml/blob/d87b7c615e5dfc93b570636c844a902e5cf8e28d/example/entry_actions.cpp) -> compiler errors
```cpp
#include <boost/sml.hpp>
#include <iostream>
#include <river/fn.hpp>

namespace sml = boost::sml;

// events
struct next {};

// states
struct s1 {};
struct s2 {};

/* clang-format on */

auto print = []() { std::cout << "lambda triggered\n"; };

void free_print() { std::cout << "free_print triggered\n"; }

class Machine {
  using Self = Machine;
  int data{0};

 public:
  auto operator()() {
    using namespace sml;
    /* clang-format off */
    return make_transition_table(
      * "idle"_s      + on_entry<_> / print  // lambda expression works
      , state<s1>     + on_entry<_> / &Self::static_print // static method fails
      , state<s2>     + on_entry<_> / &free_print// free function fails
      , "idle"_s      + event<next> = state<s1>
      , state<s1>     + event<next> = state<s2>
      , state<s2>     + event<next> = state<s1>
    );
    /* clang-format on */
  }

 private:
  static void static_print() { std::cout << "static_print triggered\n"; };
};

int main(int, char**) {
  Machine m;
  sml::sm<Machine> sm(m);

  while (true) {
    std::string input;
    std::cout << "Press [Enter] to continue, [q] to quit";
    std::getline(std::cin, input);
    if (input == "q") break;

    sm.process_event(next{});
  }
  return 0;
}
```
## Specifications

  - Version: https://github.com/rhaschke/sml/tree/issue-on-entry
  - Platform: Linux Ubuntu 20.04, gcc 9.4.0

**Comment by uyha** [comment]
https://github.com/boost-ext/sml/issues/392 maybe related

**Comment by rhaschke** [comment]
Thanks for the link! That pointed me in the right direction: We must use `sml::wrap` for those functions:
```diff
-      , state<s1>     + on_entry<_> / &Self::static_print // static method fails
-      , state<s2>     + on_entry<_> / &free_print// free function fails
+      , state<s1>     + on_entry<_> / wrap(Self::static_print)
+      , state<s2>     + on_entry<_> / wrap(free_print)
```
I didn't notice that fact before. Maybe add a note to the documentation?

**Comment by rhaschke** [comment]
What I actually wanted to achieve is calling a member function like below. This cannot be realized by a lambda or free function, because the state instance is required for calling.
@uyha, is there any way to achieve that anyway?
```cpp
#include <boost/sml.hpp>
#include <iostream>

namespace sml = boost::sml;

// events
struct next {};

// states
struct s1 {
  void on_entry() { std::cout << "member triggered\n"; }
};
struct s2 {};

class Machine {
 public:
  auto operator()() {
    using namespace sml;
    /* clang-format off */
    return make_transition_table(
      /*** using a member of the to-be-entered state doesn't work ***/
      * state<s1>     + on_entry<_> / &s1::on_entry
      , state<s1>     + event<next> = state<s2>
      , state<s2>     + event<next> = state<s1>
    );
    /* clang-format on */
  }
};

int main(int, char**) {
  Machine m;
  sml::sm<Machine> sm(m);

  while (true) {
    std::string input;
    std::cout << "Press [Enter] to continue, [q] to quit";
    std::getline(std::cin, input);
    if (input == "q") break;

    sm.process_event(next{});
  }
  return 0;
}
```

**Comment by uyha** [comment]
you have to have something like this

```cpp
s1 state1{};
Machine m;
sml::sm<Machine> sm(m, state1);
```

Since this library uses dependency injection and member functions require a hidden instance pointer, you have to provide an instance in the dependency list.

**Comment by rhaschke** [comment]
Thanks, that works! I found another solution as well: Just adding a data member variable to `s1` resolves the issue too:
```diff
-struct s1 {
-  void on_entry() { std::cout << "member triggered\n"; }
-};
+struct s1 {
+  int entered = 0;
+  void on_entry() { std::cout << "entered: " << ++entered << " times\n"; }
+};
```
Now, I can really start implementing my first SML-based machine!

**Comment by uyha** [comment]
This is a bit weird, since a class with member variables can be constructed by `sml` but an empty class cannot.

**Comment by rhaschke** [comment]
> This is a bit weird, since a class with member variables can be constructed by `sml` but an empty class cannot.

Isn't that exactly the reason why it works then? I added a member variable, which renders the class constructable by `sml`.

**Comment by uyha** [comment]
I am talking about the `sml` library itself. It’s surprising since an empty class is not automatically created but a non-empty one is.

**Comment by rhaschke** [comment]
Ok, I misunderstood you originally. I completely agree with you now :wink:
