### ISSUE TITLE
Firing two events (alternatively) from a single action

### ISSUE THREAD

**Issue by rhaschke** [boost-ext/sml#558]
## Expected Behavior
In [this example on godbolt.org](https://godbolt.org/z/c3G8cj9cv) I try to `process()` two different events.

## Actual Behavior
However, I just get compiler errors.

What's wrong there?

**Comment by uyha** [comment]
An even "cleaner" workaround https://godbolt.org/z/T35ed6Ka9

**Comment by rhaschke** [comment]
Thanks a lot for this helpful trick to declare an otherwise unknown event.

**Comment by lisean789** [comment]
> An even "cleaner" workaround https://godbolt.org/z/T35ed6Ka9

@uyha It looks like although there are no compile error for your work around, the "quit" event isn't propagated to the parent state. The only type of work around I know for now involves working from outside the state machine.
