### ISSUE TITLE
Version 1.1.7 requires C++ 20

### ISSUE THREAD

**Issue by gjasny** [boost-ext/sml#572]
Hello,

according to the readme sml is a:

> C++14 one header only State Machine Library

## Expected Behavior

Code compiles with C++ 14

## Actual Behavior

Code compiles only with C++ 20

## Steps to Reproduce the Problem

```
$ clang -std=c++14 -I include -c example/hello_world.cpp
In file included from example/hello_world.cpp:8:
include/boost/sml.hpp:425:3: error: defaulted definition of default constructor is not constexpr
  constexpr pool() = default;
  ^
include/boost/sml.hpp:1555:5: warning: use of this statement in a constexpr function is a C++20 extension [-Wc++20-extensions]
    try {
    ^
1 warning and 1 error generated.
```

## Specifications

  - Version: 1.1.7
  - Platform: macOS 13.3.1 and Xcode 14.3
  - Subsystem:

**Comment by krzysztof-jusiak** [comment]
Fixed by https://github.com/boost-ext/sml/releases/tag/v1.1.8

**Comment by gjasny** [comment]
Still broken:
```
$ git describe --tags
v1.1.8

$ clang -std=c++14 -I include -c example/hello_world.cpp
In file included from example/hello_world.cpp:8:
include/boost/sml.hpp:425:3: error: defaulted definition of default constructor is not constexpr
  constexpr pool() = default;
  ^
1 error generated.
```

**Comment by Rijom** [comment]
I'm seeing the same issue as @gjasny.

**Comment by krzysztof-jusiak** [comment]
should be fixed now by https://github.com/boost-ext/sml/commit/9d7cc3d43f1a619a84049d6786054f31d6d1ab86
