### ISSUE TITLE
Version number not updated before release

### ISSUE THREAD

**Issue by gjasny** [boost-ext/sml#574]
Hello,

both `CMakeLists.txt`:
https://github.com/boost-ext/sml/blob/8eb63a8b77bb662075dd36b316e53f75e605fd0f/CMakeLists.txt#L180

as well as `sml.hpp`"
https://github.com/boost-ext/sml/blob/8eb63a8b77bb662075dd36b316e53f75e605fd0f/include/boost/sml.hpp#L12
https://github.com/boost-ext/sml/blob/8eb63a8b77bb662075dd36b316e53f75e605fd0f/include/boost/sml.hpp#L17

contain a stale version number.

Thanks,
Gregor

**Comment by krzysztof-jusiak** [comment]
should be fixed by https://github.com/boost-ext/sml/commit/9d7cc3d43f1a619a84049d6786054f31d6d1ab86
