### ISSUE TITLE
gcc 10.5 warning: array subscript is outside array bounds

### ISSUE THREAD

**Issue by cmigliorini** [boost-ext/sml#614]
Hello, I can't seem to reproduce the following issue with a simple template (yet), but I thought perhaps someone else have encountered this so I'd create this ticket anyway. 

## Expected Behavior

SML compiles without warning

## Actual Behavior

gcc 10.5.0.1 issues warnings such as
```
sml-1.1.9/include/boost/sml.hpp:553:13: 
  warning: array subscript 0 is outside array bounds of 
  'boost::ext::sml::v1_1_9::aux::zero_wrapper<MyDep::operator()() const::<lambda(MyDep&)>, void> [1]'
   [-Warray-bounds]
```

```
sml-1.1.9/include/boost/sml.hpp:336:22: warning: array subscript 48 is outside array bounds of 'boost::ext::sml::v1_1_9::front::seq_<boost::ext::sml::v1_1_9::aux::zero_wrapper<boost::ext::sml::v1_1_9::front::seq_<boost::ext::sml::v1_1_9::aux::zero_wrapper<boost::ext::sml::v1_1_9::front::seq_<boost::ext::sml::v1_1_9::aux::zero_wrapper<boost::ext::sml::v1_1_9::front::seq_<boost::ext::sml::v1_1_9::aux::zero_wrapper<boost::ext::sml::v1_1_9::front::seq_<boost::ext::sml::v1_1_9::aux::zero_wrapper<boost::ext::sml::v1_1_9::aux::zero_wrapper<void (MyOtherDep::*)(const MyEvent&), 
 void (MyOtherDep::*)(const MyEvent&)>, void>,
 boost::ext::sml::v1_1_9::aux::zero_wrapper<MyOtherDep::operator()() const::<lambda(MyOtherDep&)>, void> >, void>,
 boost::ext::sml::v1_1_9::aux::zero_wrapper<MyOtherDep::operator()() const::<lambda(MyOtherDep&)>, void> >, void>,
 boost::ext::sml::v1_1_9::aux::zero_wrapper<MyOtherDep::operator()() const::<lambda(MyOtherDep&)>, void> >, void>,
 boost::ext::sml::v1_1_9::aux::zero_wrapper<MyOtherDep::operator()() const::<lambda(MyOtherDep&)>, void> >, void>,
 boost::ext::sml::v1_1_9::aux::zero_wrapper<MyOtherDep::operator()() const::<lambda(MyOtherDep&)>, void> > [1]' [-Warray-bounds]
```

## Steps to Reproduce the Problem

Unfortunately I was not able (yet) to recreate the problem outside of our private code.

## Specifications

  - Version: 1.1.9
  - Platform: linux x86 / linux aarch64
  - Subsystem:

**Comment by krzysztof-jusiak** [comment]
not sure exactly, but it's likely the zero_wrapper (for zero sized guards/ctions without capture). Can you try with `-DBOOST_SML_CFG_DISABLE_MIN_SIZE`? Thanks.

**Comment by cmigliorini** [comment]
That solved the problem, thanks! Should we just keep this now?

**Comment by krzysztof-jusiak** [comment]
Great, thanks for sharing. This warning is a false positive in gcc 10.5 as there is no array indexing actually happening; the only reason this wknd is there is to have zero sized guards/actions if lambda without capture (which in C++ still needs sizeof 1), so there is an array wknd used to get it to zero were possible. So, as I see it you have a few options
- Keep the BOOST_SML_CFG_DISABLE_MIN_SIZE (sizesof(sm) will increase)
- ignore the warning (sizeof(sm) will be the same as before but it's a bit smelly)
You can do just for SML
```
#pragma GCC dignostics push
#pragma GCC dignostics ignore "-Warray-bounds"
#include <boost/sml.hpp>
#pragma GCC dignostics pop
```
- update compiler to avoid the issue
- Ignore warning could be added to SML for gcc 10.5

So it depends on the trade-offs you are considering.

**Comment by cmigliorini** [comment]
Thank _you_! I would have added the `#pragma` if no answer came :), so now I can add it knowing it's truly a false positive -- btw this false positive from gcc also affect many code around, as I could see before I submitted this.
