### ISSUE TITLE
SML version change caused static assert fail in state machine constructor 

### ISSUE THREAD

**Issue by bjorn-jaes** [boost-ext/sml#617]
## Expected Behavior

As part of a reinstall I changed from version 1.1.9 of SML to the latest version 1.1.11 and expected my code to build without any issues, as it had done before on versions less than 1.1.10.

## Actual Behavior

When building the tests for my [Jay](https://github.com/bjorn-jaes/jay) library the tests fail to build with the following error message:

> In file included from /workspaces/jay/tests/../include/jay/address_claimer.hpp:19,
                 from /workspaces/jay/tests/../include/jay/address_manager.hpp:25,
                 from /workspaces/jay/tests/address_manager_test.cpp:12:
/usr/local/include/boost/sml.hpp: In instantiation of 'constexpr boost::ext::sml::v1_1_10::aux::missing_ctor_parameter<T>::operator TMissing&() const [with TMissing = jay::address_claimer::st_claiming; typename boost::ext::sml::v1_1_10::aux::enable_if<(! boost::ext::sml::v1_1_10::aux::integral_constant<bool, __is_base_of(boost::ext::sml::v1_1_10::aux::pool_type_base, U)>::value), int>::type <anonymous> = 0; T = jay::address_claimer::st_claiming]':
/usr/local/include/boost/sml.hpp:451:108:   required from 'constexpr boost::ext::sml::v1_1_10::aux::pool<Ts>::pool(boost::ext::sml::v1_1_10::aux::init, const boost::ext::sml::v1_1_10::aux::pool<TArgs ...>&) [with TArgs = {jay::address_claimer&, jay::network&}; Ts = {jay::address_claimer&, const jay::network&, jay::address_claimer::st_claiming&, jay::address_claimer::st_has_address&}]'
/usr/local/include/boost/sml.hpp:1825:132:   required from 'constexpr boost::ext::sml::v1_1_10::back::sm< <template-parameter-1-1> >::sm(TDeps&& ...) [with TDeps = {jay::address_claimer&, jay::network&}; typename boost::ext::sml::v1_1_10::aux::enable_if<((sizeof... (TDeps) > 1) && boost::ext::sml::v1_1_10::aux::is_unique<boost::ext::sml::v1_1_10::aux::type<>, TDeps ...>::value), int>::type <anonymous> = 0; TSM = boost::ext::sml::v1_1_10::back::sm_policy<jay::address_claimer, boost::ext::sml::v1_1_10::back::policies::dont_instantiate_statemachine_class>]'
/workspaces/jay/tests/../include/jay/address_manager.hpp:65:67:   required from here
/usr/local/include/boost/sml.hpp:394:53: error: static assertion failed: State Machine is missing a constructor parameter! Check out the `missing_ctor_parameter` error to see the missing type.
  394 |     static_assert(missing_ctor_parameter<TMissing>::value,
      |                                                     ^~~~~

The constructor with the missing parameter is state_machine_ in the code bellow:

```
address_manager(boost::asio::io_context &context, jay::name name, jay::network &network) : 
context_(context), network_(network), addr_claimer_(name), 
state_machine_(addr_claimer_, network), timeout_timer_(context)
```

With the state machine being declared as follows:

```
  jay::address_claimer addr_claimer_;
  boost::sml::sm<jay::address_claimer> state_machine_;
```

From I can interpret from the error message it seems to suggest that the i am missing a st_claiming instance from my constructor? Though I am not sure that is correct, as my state machine should only require an instance of an address_claimer and the only additional dependency should be a network instance.

```
  struct st_claiming{
    std::uint8_t address{J1939_NO_ADDR};
  };
```

## My Suspicions

I am a bit stuck on interpreting the error message as am not familiar enough with template coding to interpret the SML source code. I did look thought the change log to see if I could spot anything obvious and was wondering if any of the following additions might be the cause of the issue:
* BOOST_SML_CREATE_DEFAULT_CONSTRUCTIBLE_DEPS
* dont_instantiate_statemachine_class policy

This I imagine would be the most likely thing i could imagine to change the construction works. Thought I cant find any example or documentation on how anything would be that much different from before.

## Steps to Reproduce the Problem

  1. Install Boost, Canary and SML (version 1.1.10+)
  1. Download Jay Library
  1. Try and build Jay Library

## Specifications

  - Version: 1.1.10 - 1.1.11
  - Platform: Linux
  - Subsystem: GCC version 10.5.0 (Ubuntu 10.5.0-1ubuntu1~20.04)

**Comment by krzysztof-jusiak** [comment]
Yeah,  it's very likely to be related to the new policy. Looking at the diff https://github.com/boost-ext/sml/compare/v1.1.9...v1.1.10 that's pretty much all the changes in that area.

To get the old behavior, can you  try with `-DBOOST_SML_CREATE_DEFAULT_CONSTRUCTIBLE_DEPS`?

Also, would it be possible to get godbolt link with reproduction, that would defo speed up the investigation. Thanks.

**Comment by bjorn-jaes** [comment]
I created a compiler explorer project (godbolt) [here](https://godbolt.org/z/Ghh754n8W). I was able to reproduce the error there using a more minimal example from my library. I included the headers for SML version 9 and 11 in the project so that you can swap between them using the include at the start of the example.cpp file. I have not used compiler explorer that much before so didn't know if there was an easier way of including the library. In any case the code will compile on version 9 and fail on version 11.

**Comment by krzysztof-jusiak** [comment]
Thanks, that really helpful. So indeed the default behavior has changed since version 10+ to improve the required storage requirements. It should be more visible in the error message, will work on that. Unfortunately, that's a breaking change. too. There are 2 ways to fix it without changing sml.

1. Define `BOOST_SML_CREATE_DEFAULT_CONSTRUCTIBLE_DEPS ` which brings old behavior
-  https://godbolt.org/z/rshGo75Td

2. Create missing dependencies and pass them via constructor
```
  address_claimer::st_has_address st_has_address{};
  address_claimer::st_claiming st_claiming{};
  boost::sml::sm<address_claimer> state_machine_{addr_claimer_, net, st_has_address, st_claiming};
```
- https://godbolt.org/z/Kee1srbae (that should also take less storage for the state machine dependencies as there was a value and ref stored for default constructible objects)

Let me know if that works for you and if there is anything else which can be done to improve it?
