### ISSUE TITLE
Adding boost-ext-sml to conan-center-index

### ISSUE THREAD

**Issue by elvisdukaj** [boost-ext/sml#618]
Hi! Thank you for this great repo! I wanted to add this project to the conan-center-index so it can be consumed also from conan.

I created [this PR](https://github.com/conan-io/conan-center-index/pull/23490) to add boost-ext-sml. I would really appreciate if you can take a bit of time to review it and share your opinion.

This is how it looks like consuming the recipe:

```CMake
cmake_minimum_required(VERSION 3.15)
project(test_package LANGUAGES CXX)

find_package(sml REQUIRED CONFIG)

add_executable(test_package test_package.cpp)
target_link_libraries(test_package PRIVATE sml::sml)
```

To look for the package instead you need to look for `boost-ext-sml`, similarly for `boost-ext-ut`.

Let me know what you think!

**Comment by uyha** [comment]
It already exists: https://conan.io/center/recipes/sml?version=1.1.11

**Comment by elvisdukaj** [comment]
Ok thank you! I didn’t realize as the banking is pretty confusing: boost-ext-*, sml, next-sml…

Thank you for the quick feedback!
