### ISSUE TITLE
TSM template type name conflicts with AVR define

### ISSUE THREAD

**Issue by jputcu** [boost-ext/sml#625]
Trying to use on AVR plaform I'm getting following errors:
~~~~
C:\Users\joris\.conan2\p\sml3616c12de77ec\p\include\boost\sml.hpp(988,17): error: expected identifier before numeric constant
		 template <class TSM, class T, class... Ts>
~~~~

Reason is `iom128.h` contains a define: 
~~~~
/* Special Function I/O Register - SFIOR */
#define    TSM          7
~~~~

Quick fix, `#undef TSM` before including `fsm.hpp`.

## Specifications

  - Version:1.1.11
  - Platform:AVR using official Microchip avr-gcc 7.3

**Comment by jputcu** [comment]
I don't think this is a real bug, but maybe we can find a cleaner solution because this is very likely on AVR

**Comment by krzysztof-jusiak** [comment]
hmm, not sure what to do about it, `#define TSM` is kinda error prone and it would be better to be prefixed with `AVR_` or similar but if that's the only problematic name we can change `TSM` to `TSm` or something for this particular case but I'm afraid there might be more global names clashing?

**Comment by jputcu** [comment]
Currently have an example compiled with only that one undef, so I think it was the only one. (Of course don't know if a define replaced a name by a register number and compiled fine)
I think all register defines are all upper case, so having a lower case character would work, but still no garantee.

**Comment by jputcu** [comment]
Btw, `iom128.h` is provided by the compiler.

**Comment by krzysztof-jusiak** [comment]
> Btw, iom128.h is provided by the compiler.
:disappointed: 
Fix - https://github.com/boost-ext/sml/commit/0bdc4f593a3a1cc5bb45e0464c0923683d099d86 has the fix

**Comment by krzysztof-jusiak** [comment]
If you can please let me know if it works so that we can release a new version with the bug fix, thanks.

**Comment by jputcu** [comment]
Tried it and it compiles, thanks

**Comment by krzysztof-jusiak** [comment]
Thanks.
